project:
  type: website

website:
  title: "Scientific Wiki Template"
  search: true
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: "Home"
      - auto: "doc/"
      - href: https://github.com/MKReyesH/ScientificWiki
        text: "GitHub Project"
      - href: about.qmd

bibliography: bib/references.bib
csl: bib/journal-of-cosmology-and-astroparticle-physics.csl

format:
  html:
    theme: cosmo
    css: include/css-config.css
    math: mathjax
    include-in-header: 
      - include/mathjax-config.html