website:
  title: "Scientific Wiki Template"
  search: true
  sidebar:
    style: "docked"
    logo: "img/logo/logo.png"
    contents:
      - href: index.qmd
        text: "Home"
      - section: "Topics"
        contents:
        - section: "Examples"
          contents:
          - auto: "doc/Examples/*.qmd"
        - section: "Physics"
          contents:
          - auto: "doc/Physics/*.qmd"
      - href: https://github.com/MKReyesH/ScientificWiki
        text: "GitHub Project"
      - href: about.qmd

bibliography: bib/references.bib
csl: bib/journal-of-cosmology-and-astroparticle-physics.csl

project:
  type: website

filters:
  - lua/latex-to-quarto.lua
  - lua/mindmap-graph.lua

format:
  html:
    theme: cosmo
    math: mathjax
    css: include/css-config.css
    