project:
  type: website

website:
  title: "Scientific Wiki Template"
  search: true
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: "Home"
      - auto: "doc/"
      - href: https://github.com/MKReyesH/ScientificWiki
        text: "GitHub Project"
      - href: about.qmd

bibliography: bib/references.bib

format:
  html:
    theme: cosmo
    math: mathjax